export interface PresetPlaylist {
  id: string;
  name: string;
  description: string;
  icon: string;
  url: string;
  region?: string;
}

export const presetPlaylists: PresetPlaylist[] = [
  // ── Featured ──
  {
    id: 'sports',
    name: 'Sports',
    description: 'Sports channels worldwide',
    icon: '⚽',
    url: 'https://iptv-org.github.io/iptv/categories/sports.m3u',
    region: 'Featured',
  },
  {
    id: 'news',
    name: 'News',
    description: 'News channels worldwide',
    icon: '📰',
    url: 'https://iptv-org.github.io/iptv/categories/news.m3u',
    region: 'Featured',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    description: 'Entertainment channels worldwide',
    icon: '🎭',
    url: 'https://iptv-org.github.io/iptv/categories/entertainment.m3u',
    region: 'Featured',
  },
  {
    id: 'music',
    name: 'Music',
    description: 'Music channels worldwide',
    icon: '🎵',
    url: 'https://iptv-org.github.io/iptv/categories/music.m3u',
    region: 'Featured',
  },
  {
    id: 'movies',
    name: 'Movies',
    description: 'Movie channels worldwide',
    icon: '🎬',
    url: 'https://iptv-org.github.io/iptv/categories/movies.m3u',
    region: 'Featured',
  },
  {
    id: 'kids',
    name: 'Kids',
    description: 'Channels for children',
    icon: '👶',
    url: 'https://iptv-org.github.io/iptv/categories/kids.m3u',
    region: 'Featured',
  },
  // ── Asia ──
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    description: 'TV channels from Sri Lanka',
    icon: '🇱🇰',
    url: 'https://iptv-org.github.io/iptv/countries/lk.m3u',
    region: 'Asia',
  },
  {
    id: 'india',
    name: 'India',
    description: 'TV channels from India',
    icon: '🇮🇳',
    url: 'https://iptv-org.github.io/iptv/countries/in.m3u',
    region: 'Asia',
  },
  {
    id: 'japan',
    name: 'Japan',
    description: 'TV channels from Japan',
    icon: '🇯🇵',
    url: 'https://iptv-org.github.io/iptv/countries/jp.m3u',
    region: 'Asia',
  },
  {
    id: 'south-korea',
    name: 'South Korea',
    description: 'TV channels from South Korea',
    icon: '🇰🇷',
    url: 'https://iptv-org.github.io/iptv/countries/kr.m3u',
    region: 'Asia',
  },
  {
    id: 'china',
    name: 'China',
    description: 'TV channels from China',
    icon: '🇨🇳',
    url: 'https://iptv-org.github.io/iptv/countries/cn.m3u',
    region: 'Asia',
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    description: 'TV channels from Indonesia',
    icon: '🇮🇩',
    url: 'https://iptv-org.github.io/iptv/countries/id.m3u',
    region: 'Asia',
  },
  {
    id: 'thailand',
    name: 'Thailand',
    description: 'TV channels from Thailand',
    icon: '🇹🇭',
    url: 'https://iptv-org.github.io/iptv/countries/th.m3u',
    region: 'Asia',
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    description: 'TV channels from Pakistan',
    icon: '🇵🇰',
    url: 'https://iptv-org.github.io/iptv/countries/pk.m3u',
    region: 'Asia',
  },
  {
    id: 'bangladesh',
    name: 'Bangladesh',
    description: 'TV channels from Bangladesh',
    icon: '🇧🇩',
    url: 'https://iptv-org.github.io/iptv/countries/bd.m3u',
    region: 'Asia',
  },
  {
    id: 'philippines',
    name: 'Philippines',
    description: 'TV channels from Philippines',
    icon: '🇵🇭',
    url: 'https://iptv-org.github.io/iptv/countries/ph.m3u',
    region: 'Asia',
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    description: 'TV channels from Vietnam',
    icon: '🇻🇳',
    url: 'https://iptv-org.github.io/iptv/countries/vn.m3u',
    region: 'Asia',
  },
  {
    id: 'malaysia',
    name: 'Malaysia',
    description: 'TV channels from Malaysia',
    icon: '🇲🇾',
    url: 'https://iptv-org.github.io/iptv/countries/my.m3u',
    region: 'Asia',
  },
  // ── Europe ──
  {
    id: 'united-kingdom',
    name: 'United Kingdom',
    description: 'TV channels from the UK',
    icon: '🇬🇧',
    url: 'https://iptv-org.github.io/iptv/countries/uk.m3u',
    region: 'Europe',
  },
  {
    id: 'germany',
    name: 'Germany',
    description: 'TV channels from Germany',
    icon: '🇩🇪',
    url: 'https://iptv-org.github.io/iptv/countries/de.m3u',
    region: 'Europe',
  },
  {
    id: 'france',
    name: 'France',
    description: 'TV channels from France',
    icon: '🇫🇷',
    url: 'https://iptv-org.github.io/iptv/countries/fr.m3u',
    region: 'Europe',
  },
  {
    id: 'spain',
    name: 'Spain',
    description: 'TV channels from Spain',
    icon: '🇪🇸',
    url: 'https://iptv-org.github.io/iptv/countries/es.m3u',
    region: 'Europe',
  },
  {
    id: 'italy',
    name: 'Italy',
    description: 'TV channels from Italy',
    icon: '🇮🇹',
    url: 'https://iptv-org.github.io/iptv/countries/it.m3u',
    region: 'Europe',
  },
  {
    id: 'turkey',
    name: 'Turkey',
    description: 'TV channels from Turkey',
    icon: '🇹🇷',
    url: 'https://iptv-org.github.io/iptv/countries/tr.m3u',
    region: 'Europe',
  },
  {
    id: 'russia',
    name: 'Russia',
    description: 'TV channels from Russia',
    icon: '🇷🇺',
    url: 'https://iptv-org.github.io/iptv/countries/ru.m3u',
    region: 'Europe',
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    description: 'TV channels from Netherlands',
    icon: '🇳🇱',
    url: 'https://iptv-org.github.io/iptv/countries/nl.m3u',
    region: 'Europe',
  },
  {
    id: 'portugal',
    name: 'Portugal',
    description: 'TV channels from Portugal',
    icon: '🇵🇹',
    url: 'https://iptv-org.github.io/iptv/countries/pt.m3u',
    region: 'Europe',
  },
  {
    id: 'poland',
    name: 'Poland',
    description: 'TV channels from Poland',
    icon: '🇵🇱',
    url: 'https://iptv-org.github.io/iptv/countries/pl.m3u',
    region: 'Europe',
  },
  {
    id: 'greece',
    name: 'Greece',
    description: 'TV channels from Greece',
    icon: '🇬🇷',
    url: 'https://iptv-org.github.io/iptv/countries/gr.m3u',
    region: 'Europe',
  },
  {
    id: 'romania',
    name: 'Romania',
    description: 'TV channels from Romania',
    icon: '🇷🇴',
    url: 'https://iptv-org.github.io/iptv/countries/ro.m3u',
    region: 'Europe',
  },
  // ── Americas ──
  {
    id: 'united-states',
    name: 'United States',
    description: 'TV channels from the US',
    icon: '🇺🇸',
    url: 'https://iptv-org.github.io/iptv/countries/us.m3u',
    region: 'Americas',
  },
  {
    id: 'canada',
    name: 'Canada',
    description: 'TV channels from Canada',
    icon: '🇨🇦',
    url: 'https://iptv-org.github.io/iptv/countries/ca.m3u',
    region: 'Americas',
  },
  {
    id: 'brazil',
    name: 'Brazil',
    description: 'TV channels from Brazil',
    icon: '🇧🇷',
    url: 'https://iptv-org.github.io/iptv/countries/br.m3u',
    region: 'Americas',
  },
  {
    id: 'mexico',
    name: 'Mexico',
    description: 'TV channels from Mexico',
    icon: '🇲🇽',
    url: 'https://iptv-org.github.io/iptv/countries/mx.m3u',
    region: 'Americas',
  },
  {
    id: 'argentina',
    name: 'Argentina',
    description: 'TV channels from Argentina',
    icon: '🇦🇷',
    url: 'https://iptv-org.github.io/iptv/countries/ar.m3u',
    region: 'Americas',
  },
  {
    id: 'colombia',
    name: 'Colombia',
    description: 'TV channels from Colombia',
    icon: '🇨🇴',
    url: 'https://iptv-org.github.io/iptv/countries/co.m3u',
    region: 'Americas',
  },
  {
    id: 'chile',
    name: 'Chile',
    description: 'TV channels from Chile',
    icon: '🇨🇱',
    url: 'https://iptv-org.github.io/iptv/countries/cl.m3u',
    region: 'Americas',
  },
  {
    id: 'peru',
    name: 'Peru',
    description: 'TV channels from Peru',
    icon: '🇵🇪',
    url: 'https://iptv-org.github.io/iptv/countries/pe.m3u',
    region: 'Americas',
  },
  // ── Middle East & Africa ──
  {
    id: 'saudi-arabia',
    name: 'Saudi Arabia',
    description: 'TV channels from Saudi Arabia',
    icon: '🇸🇦',
    url: 'https://iptv-org.github.io/iptv/countries/sa.m3u',
    region: 'Middle East & Africa',
  },
  {
    id: 'uae',
    name: 'United Arab Emirates',
    description: 'TV channels from the UAE',
    icon: '🇦🇪',
    url: 'https://iptv-org.github.io/iptv/countries/ae.m3u',
    region: 'Middle East & Africa',
  },
  {
    id: 'egypt',
    name: 'Egypt',
    description: 'TV channels from Egypt',
    icon: '🇪🇬',
    url: 'https://iptv-org.github.io/iptv/countries/eg.m3u',
    region: 'Middle East & Africa',
  },
  {
    id: 'south-africa',
    name: 'South Africa',
    description: 'TV channels from South Africa',
    icon: '🇿🇦',
    url: 'https://iptv-org.github.io/iptv/countries/za.m3u',
    region: 'Middle East & Africa',
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    description: 'TV channels from Nigeria',
    icon: '🇳🇬',
    url: 'https://iptv-org.github.io/iptv/countries/ng.m3u',
    region: 'Middle East & Africa',
  },
  {
    id: 'israel',
    name: 'Israel',
    description: 'TV channels from Israel',
    icon: '🇮🇱',
    url: 'https://iptv-org.github.io/iptv/countries/il.m3u',
    region: 'Middle East & Africa',
  },
  {
    id: 'iran',
    name: 'Iran',
    description: 'TV channels from Iran',
    icon: '🇮🇷',
    url: 'https://iptv-org.github.io/iptv/countries/ir.m3u',
    region: 'Middle East & Africa',
  },
  // ── Oceania ──
  {
    id: 'australia',
    name: 'Australia',
    description: 'TV channels from Australia',
    icon: '🇦🇺',
    url: 'https://iptv-org.github.io/iptv/countries/au.m3u',
    region: 'Oceania',
  },
  {
    id: 'new-zealand',
    name: 'New Zealand',
    description: 'TV channels from New Zealand',
    icon: '🇳🇿',
    url: 'https://iptv-org.github.io/iptv/countries/nz.m3u',
    region: 'Oceania',
  },
];
